In [18]:
import tensorcircuit as tc
import tensorflow as ts 
import numpy as np
import math
from numpy import linalg as LA

tc.set_backend("tensorflow")

def i_iterate_multiplication(n):
    tmp = 1
    for i in range(n):
        tmp = np.kron(I, tmp)
    return tmp

n = 3
# h_i = 1
H = 0
theta = math.pi/2
min_w = 999
I = tc.gates._i_matrix
X = tc.gates._x_matrix  
Y = tc.gates._y_matrix  
Z = tc.gates._z_matrix 

for h_i in range(0, 20):
    for i in range(0, n-1):
        H = H - np.kron(np.kron(i_iterate_multiplication(i), np.kron(Z, Z)), i_iterate_multiplication(n-2-i))
    for i in range(0, n):
        H = H + h_i * (np.kron(np.kron(i_iterate_multiplication(i), X), i_iterate_multiplication(n-1-i)))
    # print(H)

    w, v = LA.eig(H)

    for i in range(0, len(w)):
        if w[i] < min_w:
            min_w = w[i]
    print(h_i)
    print(min_w)
    min_w = 999
    H = 0

0
-2.0
1
-3.4939592074349317
2
-6.249770839529159
3
-9.166635402827085
4
-12.12499248932782
5
-15.09999752493564
6
-18.083332335604098
7
-21.071428108961058
8
-24.062499762511834
9
-27.05555542365828
10
-30.049999922070175
11
-33.045454497045235
12
-36.041666635324475
13
-39.038461517451324
14
-42.035714271206714
15
-45.03333332305672
16
-48.03124999255666
17
-51.02941175920829
18
-54.027777773646385
19
-57.02631578632071


In [10]:
def make_list(t, n):
    for i in range(n):
        t.append(np.roll(t[-1], 1))
n = 3
h_i = 1
a = [[0 for i in range(n)]]
a[0][0] = 3
a[0][1] = 3
b = [[0 for i in range(n)]]
b[0][0] = 1
make_list(a, n-2)
make_list(b, n-1)

H_1 = tc.quantum.PauliStringSum2COO(np.array(a + b), numpy = False)
print(H_1)

2022-07-26 19:46:31.985164: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-07-26 19:46:31.985183: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-07-26 19:46:31.985209: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (imasonliu-LC1): /proc/driver/nvidia/version does not exist
2022-07-26 19:46:31.985377: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [0 4]
 [1 0]
 [1 3]
 [1 5]
 [2 0]
 [2 2]
 [2 3]
 [2 6]
 [3 1]
 [3 2]
 [3 7]
 [4 0]
 [4 5]
 [4 6]
 [5 1]
 [5 4]
 [5 5]
 [5 7]
 [6 2]
 [6 4]
 [6 7]
 [7 3]
 [7 5]
 [7 6]
 [7 7]], shape=(28, 2), dtype=int64), values=tf.Tensor(
[ 2.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j -2.+0.j
  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j
  1.+0.j -2.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j
  2.+0.j], shape=(28,), dtype=complex64), dense_shape=tf.Tensor([8 8], shape=(2,), dtype=int64))


2022-07-26 19:46:32.365226: I tensorflow/compiler/xla/service/service.cc:170] XLA service 0x557999d23000 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-07-26 19:46:32.365313: I tensorflow/compiler/xla/service/service.cc:178]   StreamExecutor device (0): Host, Default Version
2022-07-26 19:46:32.432914: I tensorflow/compiler/jit/xla_compilation_cache.cc:478] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
