In [43]:
import tensorcircuit as tc
import tensorflow as ts 
import numpy as np
import math

tc.set_backend("tensorflow")

def i_iterate_multiplication(n):
    tmp = 1
    for i in range(n):
        tmp = np.kron(I, tmp)
    return tmp

n = 3
h_i = 1
H = 0
theta = math.pi/2
I = tc.gates._i_matrix
X = tc.gates._x_matrix  
Y = tc.gates._y_matrix  
Z = tc.gates._z_matrix 

for i in range(0, n-1):
    H = H - np.kron(np.kron(i_iterate_multiplication(i), np.kron(Z, Z)), i_iterate_multiplication(n-2-i))
for i in range(0, n):
    H = H + h_i * (np.kron(np.kron(i_iterate_multiplication(i), X), i_iterate_multiplication(n-1-i)))
print(H)

[[-2.  1.  1.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  1.  0.  1.  0.  0.]
 [ 1.  0.  2.  1.  0.  0.  1.  0.]
 [ 0.  1.  1.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  1.  1.  0.]
 [ 0.  1.  0.  0.  1.  2.  0.  1.]
 [ 0.  0.  1.  0.  1.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  1.  1. -2.]]


In [86]:
def make_list(t, n):
    for i in range(n):
        t.append(np.roll(t[-1], 1))
n = 3
h_i = 1
a = [[0 for i in range(n)]]
a[0][0] = 3
a[0][1] = 3
b = [[0 for i in range(n)]]
b[0][0] = 1
make_list(a, n-2)
make_list(b, n-1)

H_1 = tc.quantum.PauliStringSum2COO(np.array(a + b), numpy = False)
print(H_1)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [0 4]
 [1 0]
 [1 3]
 [1 5]
 [2 0]
 [2 2]
 [2 3]
 [2 6]
 [3 1]
 [3 2]
 [3 7]
 [4 0]
 [4 5]
 [4 6]
 [5 1]
 [5 4]
 [5 5]
 [5 7]
 [6 2]
 [6 4]
 [6 7]
 [7 3]
 [7 5]
 [7 6]
 [7 7]], shape=(28, 2), dtype=int64), values=tf.Tensor(
[ 2.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j -2.+0.j
  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j
  1.+0.j -2.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j  1.+0.j
  2.+0.j], shape=(28,), dtype=complex64), dense_shape=tf.Tensor([8 8], shape=(2,), dtype=int64))
